routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



#Route::get('/profile', function () {
#    return view('rotating_card.partials.rowcard');
#});

Auth::routes();

Route::resource('posts', 'PostController');
Route::resource('comments', 'CommentController');
Route::resource('users', 'UserController');
#Route::resource('pekan', 'PekanController');
Route::resource('kehadiran', 'KehadiranController');
Route::resource('post', 'KelompokController');

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', 'HomeController@index')->name('home');

// DomPDF
Route::get('/test-dompdf', function () {
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Test</h1>');
    return $pdf->stream();
});

Route::get('/likepost/{id}/{user_id}', 'PostController@likepost');
Route::get('/likecomment/{id}/{user_id}', 'CommentController@likecomment');
Route::get('/follow/{id}/{user_id}', 'UserController@follow');
Route::get('/follow2/{id}/{user_id}', 'UserController@followtoprofile');
#userid di sini adalah pelaku liker,dan follower
Route::get('/mypost', 'PostController@mypost');

Route::get('/commentlangsung/{post_id}/', 'CommentController@commentlangsung');
Route::post('/storelangsung', 'CommentController@storelangsung');
Route::get('/profile', 'UserController@indexprofile');


#Route::get('/index2', function () {
#    return view('posts.index2');
#});

Route::get('/index2','PostController@daftarpost2');
Route::get('/autoisi','KehadiranController@autoisi');
Route::get('/inputpresensi','KehadiranController@inputpresensi');
Route::post('/updatepresensi','KehadiranController@updatepresensi');

resources/views/rotating_card/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <title> Social Media Project </title>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <link href='{{asset('/rotating_card/css/bootstrap.css')}}' rel='stylesheet' />

    <link href="{{asset('/rotating_card/css/pe-icon-7-stroke.css')}}" rel="stylesheet" />

<!--     <link href='css/ct-navbar.css' rel='stylesheet' /> -->
    <link href='{{ asset('/rotating_card/css/rotating-card.css') }}' rel='stylesheet' />

<!--     untuk tampilan card post tapi conflic dengan yang lain -->
<!--         <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <style>
        body{
            margin-top: 100px;
        }
        .navbar-default .navbar-nav > li > a{
            padding: 15px 15px;
            margin: 5px 0;
        }

        .navbar-default{
            padding: 10px 0;
            background-color: rgba(255, 255, 255, 0.95);
            border-color: transparent;
            box-shadow: 0 0px 13px rgba(0,0,0,.2);
        }
        .btn-info,
        .btn-info:hover,
        .btn-info:focus{
            color: #FFF !important;
            background-color: #00bbff !important;
            border-color: #00bbff !important;
        }

        .btn-info{
            opacity: .8;
            transition: all 0.1s;
            -webkit-transition: all 0.1s;
        }
        .btn-info:hover,
        .btn-info:focus{
            opacity: 1;
        }

        
    </style>
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
    @include('rotating_card.side_bar')


<div class="container">

    {{-- navbar --}}
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand navbar-brand-logo" href="https://www.instagram.com/dhs.bandung/?hl=en">
                <div class="navbar-brand">
                    <img src="{{ asset('/rotating_card/images/LogoDHS.png') }}" class="img-responsive">
                </div>
                <div class="brand"></div>
          </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link " href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link btn btn-info" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>
        
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
        
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    

{{-- cards --}}
@yield('content')

    <div class="space-200"></div>
</div>

   
    <div class="space-1"></div>
    <p class="text-center">Copyright &copy; 2021 <a href="https://sanbercode.com">Team #10</a>, made with <i class="fa fa-heart ct-heart"></i> for a better web.</p>
   </div>



<script src="{{asset('/rotating_card/js/jquery-1.10.2.js')}}" type="text/javascript"></script>
<script src="{{asset('/rotating_card/js/bootstrap.min.js')}}" type="text/javascript"></script>

<script type="text/javascript">
    $().ready(function(){
        $('[rel="tooltip"]').tooltip();

        $('a.scroll-down').click(function(e){
            e.preventDefault();
            scroll_target = $(this).data('href');
             $('html, body').animate({
                 scrollTop: $(scroll_target).offset().top - 60
             }, 1000);
        });

    });

    function rotateCard(btn){
        var $card = $(btn).closest('.card-container');
        console.log($card);
        if($card.hasClass('hover')){
            $card.removeClass('hover');
        } else {
            $card.addClass('hover');
        }
    }

    
<!-- jQuery -->
<script src=" {{ asset('/adminlte/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src=" {{ asset('/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src=" {{ asset('/adminlte/dist/js/adminlte.min.js ')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src=" {{ asset('/adminlte/dist/js/demo.js')}}"></script>

@stack('scripts')


</script>

</body>
</html>

resources/views/rotating_card/side_bar.blade.php
<style>
    .sidebar{
        top: 100px;
  left: 50px;
  right: 0px;
  width: 50%;
  display: flex;
  justify-content: space-between;
  margin: 0 auto;

    }
     
</style>
  
      <!-- Sidebar Menu -->
      <header>
        <div class="sidebar">
        <a href="{{ route('posts.index') }}" class="nav-link">
            <p>Post</p>
        </a>
        <a href="{{ route('comments.index')}}" class="nav-link">
            <p>Comment</p>
        </a>
        <a href="{{ asset('/profile') }}" class="nav-link">
        <p>Profile</p>
        </a>
        <a href="{{ route('users.index') }}" class="nav-link">
            <p>User</p>
        </a>
     
        </div>
     </header>
        
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library --> 
               <!--
          <li class="nav-item has-treeview">
            
            <ul class="nav nav-treeview">
              <li class="nav-item">
                
              </li>
              <li class="nav-item">
                <a href="{{ route('users.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>User</p>
                </a>
              </li>
            </ul>
          </li>
          
            
        </ul> -->

        

<!-- Page content -->
<div class="content">
  ..
</div>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>